language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.3
  - android-23
  - add-on
  - extra
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - addon-google_apis-google-19

deploy:
    provider: releases
    apikey: $GITHUB_KEY
    file: app/build/outputs/apk/app-release.apk
    skip_cleanup: true
    on:
      tags: true

notifications:
    email:
        recipients:
            - fandras90@address.com
        on_success: always
        on_failure: always

script: ./gradlew :app:build